[project]
name = "memorylane"
version = "0.1.0"
description = ""
authors = [
    {name = "AgostaGiorgio",email = "agogi.dev@gmail.com"}
]
readme = "README.md"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
